import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, "src", "data", "catalog.json");
const generatedDir = path.join(root, "src", "generated");
const checkOnly = process.argv.includes("--check");
const catalog = JSON.parse(await readFile(sourcePath, "utf8"));

const coreTypes = {
  ApiUri: "string | null",
  APIURI: "string | null",
  ID: "number | null",
  Id: "number | null",
  CreateDate: "string | null",
  DateCreated: "string | null",
  UpdateDate: "string | null",
  DateUpdated: "string | null",
  OwnerID: "number | null",
  TenantID: "number | null",
  ProspectID: "number | null",
  VendorID: "number | null",
  PropertyID: "number | null",
  ContactID: "number | null",
  TaskID: "number | null",
  UnitID: "number | null",
  LeaseID: "number | null",
  UserID: "number | null",
  LocationID: "number | null",
  PropertyGroupID: "number | null",
  AmenityID: "number | null",
  UnitAmenityID: "number | null",
  GLAccountID: "number | null",
  ChargeTypeID: "number | null",
  UnitTypeID: "number | null",
  TransactionID: "number | null",
  HistoryID: "number | null",
  OwnerCheckID: "number | null",
  PaymentID: "number | null",
  ChargeID: "number | null",
  RecurringChargeID: "number | null",
  UserDefinedFieldID: "number | null",
  UserDefinedValueID: "number | null",
  ServiceManagerStatusID: "number | null",
  ServiceManagerCategoryID: "number | null",
  ServiceManagerPriorityID: "number | null",
  ServiceManagerIssueID: "number | null",
  ReportWriterReportID: "number | null",
  Name: "string | null",
  CompanyName: "string | null",
  FirstName: "string | null",
  LastName: "string | null",
  Email: "string | null",
  Title: "string | null",
  Description: "string | null",
  Note: "string | null",
  NoteText: "string | null",
  Username: "string | null",
  ShortName: "string | null",
  UnitNumber: "string | null",
  AccountNumber: "string | null",
  TransactionDate: "string | null",
  HistoryDate: "string | null",
  CheckDate: "string | null",
  MoveInDate: "string | null",
  MoveOutDate: "string | null",
  DueDate: "string | null",
  BillDate: "string | null",
  Amount: "number | null",
  ActualAmount: "number | null",
  OriginalAmount: "number | null",
  CurrentBalance: "number | null",
  SortOrder: "number | null",
  IsActive: "boolean | null",
  IsClosed: "boolean | null",
  Selected: "boolean | null",
  Value: "unknown",
};

function camelCase(value) {
  return value.replace(/_([a-z0-9])/g, (_, letter) => letter.toUpperCase());
}

function banner(source) {
  return `// Generated by scripts/generate-catalog.mjs from ${source}. Do not edit by hand.\n`;
}

const baseFields = new Set(catalog.model_fields.RMBaseModel ?? []);
const modelNames = Object.keys(catalog.model_fields).filter((name) => name !== "RMBaseModel");
const modelLines = [
  banner("src/data/catalog.json"),
  'import { RMBaseModel } from "../models-base.js";',
  "",
];

for (const modelName of modelNames) {
  modelLines.push(`export class ${modelName} extends RMBaseModel {`);
  for (const field of catalog.model_fields[modelName]) {
    if (baseFields.has(field)) continue;
    modelLines.push(`  declare ${field}?: ${coreTypes[field] ?? "unknown"};`);
  }
  modelLines.push("}", "");
}

modelLines.push("export const MODEL_CONSTRUCTORS = {");
for (const modelName of modelNames) {
  modelLines.push(`  ${JSON.stringify(modelName)}: ${modelName},`);
}
modelLines.push("} as const;", "");
modelLines.push("export type GeneratedModelName = keyof typeof MODEL_CONSTRUCTORS;", "");

const resourceLines = [
  banner("src/data/catalog.json"),
  'import type { ResourceClient } from "../resource.js";',
  'import { Resource } from "../resource.js";',
  'import * as models from "./models.js";',
  "",
];

for (const spec of catalog.resource_specs) {
  resourceLines.push(
    `export class ${spec.resource_class_name} extends Resource<models.${spec.model_name}> {`,
    "  constructor(client: ResourceClient) {",
    `    super(client, ${JSON.stringify(spec.path)}, models.${spec.model_name});`,
    "  }",
    "}",
    "",
  );
}

resourceLines.push("export interface GeneratedResourceProperties {");
for (const spec of catalog.resource_specs) {
  const camel = camelCase(spec.client_attr);
  resourceLines.push(`  ${spec.client_attr}: ${spec.resource_class_name};`);
  if (camel !== spec.client_attr) {
    resourceLines.push(`  ${camel}: ${spec.resource_class_name};`);
  }
}
resourceLines.push("}", "");

resourceLines.push("export const GENERATED_RESOURCE_DEFINITIONS = [");
for (const spec of catalog.resource_specs) {
  resourceLines.push(
    `  { clientAttr: ${JSON.stringify(spec.client_attr)}, camelAttr: ${JSON.stringify(camelCase(spec.client_attr))}, path: ${JSON.stringify(spec.path)}, modelName: ${JSON.stringify(spec.model_name)}, ResourceClass: ${spec.resource_class_name} },`,
  );
}
resourceLines.push("] as const;", "");

const resourceSpecs = catalog.resource_specs.map((spec) => ({
  module: spec.module,
  path: spec.path,
  model_name: spec.model_name,
  resource_class_name: spec.resource_class_name,
  client_attr: spec.client_attr,
  fields: spec.fields,
  ...(spec.operations ? { operations: spec.operations } : { endpoints: spec.endpoints }),
}));

const catalogLines = [
  banner("src/data/catalog.json"),
  `export const RESOURCE_SPECS = ${JSON.stringify(resourceSpecs, null, 2)} as const;`,
  "",
  `export const MODEL_FIELDS = ${JSON.stringify(catalog.model_fields, null, 2)} as const;`,
  "",
  `export const ENDPOINTS = ${JSON.stringify(catalog.endpoints, null, 2)} as const;`,
  "",
];

const outputs = new Map([
  [path.join(generatedDir, "models.ts"), modelLines.join("\n")],
  [path.join(generatedDir, "resources.ts"), resourceLines.join("\n")],
  [path.join(generatedDir, "catalog.ts"), catalogLines.join("\n")],
]);

let stale = false;
for (const [file, content] of outputs) {
  let current = null;
  try {
    current = await readFile(file, "utf8");
  } catch {
    // A missing generated file is stale.
  }
  if (current === content) continue;
  stale = true;
  if (!checkOnly) {
    await writeFile(file, content, "utf8");
    console.log(`generated ${path.relative(root, file)}`);
  }
}

if (checkOnly && stale) {
  console.error("Generated catalog sources are stale. Run npm run generate.");
  process.exitCode = 1;
}
